global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'sonarqube-exporter'
    metrics_path: '/'
    static_configs:
      - targets: ['sonarqube-exporter:8198']

      ####
# alerting:
#   alertmanagers:
#   - static_configs:
#     - targets:
#       - alertmanager:9093
# rule_files:
#   - 'rules/*.yml'